name: Deploy Angular to GitHub Pages

on:
  workflow_dispatch:  # Ручной запуск

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозиторий
        uses: actions/checkout@v4

      - name: Установка Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # Или нужная версия

      - name: Установка зависимостей
        run: npm install

      - name: Сборка Angular
        run: npx ng build --configuration=production --base-href "/v18"

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/v18
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}  # Добавляем токен
          clean: true  # Очищаем целевую ветку перед деплоем
          single-commit: true  # Используем один коммит вместо истории

